/** Server-side checkout orchestration (admin client — bypasses RLS). */
import type { SupabaseClient } from '@supabase/supabase-js';
import { CustomerRepository, OrderRepository, CouponRepository, ProductRepository } from '@/lib/db';
import { validateCoupon } from '@/lib/server/coupons';
import { getMethodsForCity, getDeliveryFee } from '@/lib/server/shipping';
import { calcSubtotal, calcDiscount, calcFinalTotal, roundMoney } from '@/lib/utils/pricing';
import { notificationService } from '@/lib/services/notificationService';
import type { CustomerRow, OrderRow } from '@/lib/supabase/types';

export interface CheckoutItem {
  productId: string;
  productName: string;
  productImage: string;
  qty: number;
  unitPrice: number;
}
export interface CheckoutPayload {
  fullName: string;
  phone: string;
  email?: string;
  address: string;
  city: string;
  deliveryMethodId: string;
  couponCode?: string;
  notes?: string;
  items: CheckoutItem[];
}
export interface CheckoutResult {
  order: OrderRow;
  customer: CustomerRow;
}
/**
 * Find an existing customer by email (case-insensitive) and update it,
 * or create a new customer. Never creates a duplicate for an existing email.
 * Returns { customer, isNew }.
 */
async function findOrCreateCustomer(
  admin: SupabaseClient,
  fullName: string,
  phone: string,
  email?: string
): Promise<{ customer: CustomerRow; isNew: boolean }> {
  const repo = new CustomerRepository(admin);
  const safeEmail = (email ?? '').trim();

  if (safeEmail) {
    const { data: existing, error: findErr } = await repo.findByEmail(safeEmail);
    if (findErr && findErr.code !== 'PGRST116') throw findErr; // PGRST116 = no rows
    if (existing) {
      const { data: updated } = await repo.update(existing.id, {
        name: fullName || existing.name,
        phone: phone || existing.phone,
        ...(safeEmail ? { email: safeEmail } : {}),
      });
      return { customer: (updated ?? existing) as CustomerRow, isNew: false };
    }
  }

  const { data: created } = await repo.create({ name: fullName, email: safeEmail || null, phone: phone || null });
  return { customer: created as CustomerRow, isNew: true };
}
// Read the store-wide free-shipping threshold (string stored in settings).
async function getGlobalFreeThreshold(admin: SupabaseClient): Promise<number> {
  const { data, error } = await admin
    .from('store_settings')
    .select('value')
    .eq('key', 'free_shipping_threshold')
    .single();
  if (error) return 0;
  return Number((data as { value: string } | null)?.value ?? 0) || 0;
}

export async function createOrder(
  admin: SupabaseClient,
  payload: CheckoutPayload
): Promise<CheckoutResult> {
  if (!payload.items || payload.items.length === 0) {
    throw new Error('Order must contain at least one item');
  }

  const subtotal = calcSubtotal(payload.items.map((i) => ({ price: i.unitPrice, qty: i.qty })));

  // --- Validate coupon SERVER-SIDE (never trust frontend) ---
  const cv = await validateCoupon(admin, payload.couponCode, {
    subtotal,
    productIds: payload.items.map((i) => i.productId),
  });
  if (payload.couponCode && !cv.valid) {
    throw new Error(cv.reason ?? 'Invalid coupon code');
  }

  // --- Resolve delivery from DB (no hard-coded prices) ---
  const globalT = await getGlobalFreeThreshold(admin);
  const methods = await getMethodsForCity(admin, payload.city);
  const method = methods.find((m) => m.id === payload.deliveryMethodId);
  if (!method) throw new Error('No delivery option available for this city');
  let deliveryFee = roundMoney(getDeliveryFee(method, subtotal, globalT > 0 ? globalT : null));

  // --- Free shipping coupon zeroes out delivery fee ---
  const isFreeShipping = cv.valid && cv.coupon?.discount_type === 'free_shipping';
  if (isFreeShipping) {
    deliveryFee = 0;
  }

  // --- Totals via single shared util ---
  const discount = cv.valid ? calcDiscount(subtotal, cv.coupon ?? null) : 0;
  const total = calcFinalTotal({ subtotal, deliveryFee, discount });

  // --- Find-or-create customer (admin; never duplicate) ---
  const { customer, isNew } = await findOrCreateCustomer(
    admin, payload.fullName, payload.phone, payload.email
  );

  // --- Create order (admin client; order_number auto-generated by DB) ---
  const orderRepo = new OrderRepository(admin);
  const address = {
    name: payload.fullName,
    phone: payload.phone,
    address: payload.address,
    city: payload.city,
    email: payload.email ?? null,
  };
  const { data: order, error: orderErr } = await orderRepo.create({
    customer_id: customer.id,
    customer_name: payload.fullName,
    customer_email: payload.email ?? '',
    customer_phone: payload.phone,
    subtotal,
    discount,
    shipping_cost: deliveryFee,
    total,
    payment_method: 'cash_on_delivery',
    shipping_address: address,
    billing_address: address,
    delivery_method: method.name,
    coupon_code: cv.valid && payload.couponCode ? payload.couponCode : null,
    notes: payload.notes ?? null,
  });
  if (orderErr || !order) throw orderErr || new Error('Failed to create order');

  // --- Add order items ---
  for (const item of payload.items) {
    await orderRepo.addItem({
      order_id: order.id,
      product_id: item.productId || null,
      product_name: item.productName,
      product_image: item.productImage || '',
      quantity: item.qty,
      unit_price: item.unitPrice,
      total: roundMoney(item.unitPrice * item.qty),
    });
  }

  // --- Atomically decrement stock (check + decrement in ONE DB statement) ---
  // This prevents the race condition where two concurrent requests both see
  // stock=1, both pass the check, and both create orders (overselling).
  const productRepo = new ProductRepository(admin);
  for (const item of payload.items) {
    if (!item.productId) continue;
    const { success } = await productRepo.decrementStock(item.productId, item.qty);
    if (!success) {
      // Rollback: delete the order we just created
      await orderRepo.delete(order.id);
      throw new Error(`Insufficient stock for "${item.productName}". Another customer may have purchased it.`);
    }
  }

  // --- Increment coupon usage ---
  if (cv.valid && cv.coupon) {
    await new CouponRepository(admin).incrementUsage(cv.coupon.id);
    // Notify that coupon was used
    try {
      await notificationService.notifyCouponUsed(
        cv.coupon.id,
        payload.couponCode!,
        order.order_number,
        payload.fullName,
        discount,
        cv.coupon.discount_type,
      );
    } catch (e) {
      console.error('Failed to send coupon used notification:', e);
    }
  }

  // --- Record order timeline entry ---
  await admin.from('order_timeline').insert({
    order_id: order.id,
    status: 'pending',
    note: isNew
      ? `New customer. Order placed.`
      : `Order placed.`,
  });

  // --- Send notifications ---
  try {
    await notificationService.notifyNewOrder(order.id, order.order_number, payload.fullName, total);
    if (isNew) {
      await notificationService.notifyNewCustomer(customer.id, payload.fullName, payload.email ?? '');
    }
    // Check stock levels after decrement
    for (const item of payload.items) {
      if (!item.productId) continue;
      const { data: updatedProduct } = await admin.from('products').select('stock, low_stock_threshold').eq('id', item.productId).single();
      if (updatedProduct) {
        const stock = Number(updatedProduct.stock);
        const threshold = Number(updatedProduct.low_stock_threshold ?? 10);
        if (stock <= 0) {
          await notificationService.notifyOutOfStock(item.productId, item.productName);
        } else if (stock <= threshold) {
          await notificationService.notifyLowStock(item.productId, item.productName, stock, threshold);
        }
      }
    }
  } catch (e) {
    console.error('Failed to send checkout notifications:', e);
  }

  return { order: order as OrderRow, customer };
}
