// lib/toast/ToastContainer.tsx
'use client';

import { useToast } from './useToast';
import { useToastSettings } from './ToastSettingsContext';
import type { ToastPosition } from './ToastSettingsContext';
import { Toast } from './Toast';

/* Static Tailwind utilities per position. A dynamic class like
   `toast-${settings.position}` is never generated by Tailwind (it only
   emits classes found verbatim in source), which is why changing the
   position setting previously had no effect. */
const POSITION_CLASSES: Record<ToastPosition, string> = {
  'top-right': 'top-4 right-4 sm:right-6',
  'top-left': 'top-4 left-4 sm:left-6',
  'top-center': 'top-4 left-1/2 -translate-x-1/2',
  'bottom-right': 'bottom-4 right-4 sm:right-6',
  'bottom-left': 'bottom-4 left-4 sm:left-6',
  'bottom-center': 'bottom-4 left-1/2 -translate-x-1/2',
};

export function ToastContainer() {
  const { toasts, removeToast } = useToast();
  const { settings } = useToastSettings();

  if (toasts.length === 0) return null;

  return (
    <div
      className={`fixed z-[9999] flex w-full max-w-md flex-col gap-3 pointer-events-none ${
        POSITION_CLASSES[settings.position] ?? POSITION_CLASSES['top-right']
      }`}
    >
      {toasts.map((toast) => (
        <div key={toast.id} className="pointer-events-auto">
          <Toast toast={toast} onRemove={removeToast} />
        </div>
      ))}
    </div>
  );
}
